### ISSUE TITLE
get_accuracy(y, pred, th=0.5) in your work has a bug

### ISSUE THREAD

**Issue by kechan** [kool7/AI_For_Medical_Diagnosis_2020#1]
For all TP, FP, ...

  TP = true_positives(y, pred, th=0.5)

You are hard coding passing th = 0.5, and not using the input argument th from get_accuracy(...)

This should be corrected to:

  TP = true_positives(y, pred, th=th)
  Etc. etc.

**Comment by kool7** [comment]
Fixed.
